#include "test_harness.hh"
#include "nfsim_transform_decoder.hh"
using namespace NFcore2;
namespace { NFsimPublicTransformView v(int k,unsigned r,unsigned c){NFsimPublicTransformView x;x.kind=k;x.reactant=r;x.component=c;return x;} }
TEST(TransformDecoder_StateChangePreservesFinalValue){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView x=v(NATIVE_STATE_CHANGE,0,2);x.final_state=7;a[0].push_back(x);std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),1u);EXPECT_EQ(o[0].new_value,7);}
TEST(TransformDecoder_IncrementAndDecrementPreserved){std::vector<std::vector<NFsimPublicTransformView> > a(1);a[0].push_back(v(NATIVE_INCREMENT_STATE,0,0));a[0].push_back(v(NATIVE_DECREMENT_STATE,0,1));std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o[0].kind,NATIVE_INCREMENT_STATE);EXPECT_EQ(o[1].kind,NATIVE_DECREMENT_STATE);}
TEST(TransformDecoder_UnbindRequestsRuntimePartnerInference){std::vector<std::vector<NFsimPublicTransformView> > a(1);a[0].push_back(v(NATIVE_UNBINDING,0,1));std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),1u);EXPECT_EQ(o[0].other_component,NATIVE_INFER_PARTNER_COMPONENT);}
TEST(TransformDecoder_BindingFirstHalfResolvesSecondHalfComponent){std::vector<std::vector<NFsimPublicTransformView> > a(2);NFsimPublicTransformView first=v(NATIVE_BINDING,0,1);first.other_reactant=1;first.other_mapping_index=0;a[0].push_back(first);NFsimPublicTransformView second=v(NATIVE_BINDING,1,2);second.second_binding_half=true;a[1].push_back(second);std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),1u);EXPECT_EQ(o[0].reactant,0u);EXPECT_EQ(o[0].component,1u);EXPECT_EQ(o[0].other_reactant,1u);EXPECT_EQ(o[0].other_component,2u);}
TEST(TransformDecoder_SameReactantBindingUsesMappingIndexExactly){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView first=v(NATIVE_BINDING,0,0);first.other_reactant=0;first.other_mapping_index=1;a[0].push_back(first);NFsimPublicTransformView second=v(NATIVE_BINDING,0,3);second.second_binding_half=true;a[0].push_back(second);std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),1u);EXPECT_EQ(o[0].other_component,3u);}
TEST(TransformDecoder_RejectsBindingPartnerReactantOutOfRange){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView first=v(NATIVE_BINDING,0,0);first.other_reactant=3;first.other_mapping_index=0;a[0].push_back(first);EXPECT_THROW(NFsimTransformDecoder::decode(a),std::out_of_range);}
TEST(TransformDecoder_RejectsBindingPartnerMappingOutOfRange){std::vector<std::vector<NFsimPublicTransformView> > a(2);NFsimPublicTransformView first=v(NATIVE_BINDING,0,0);first.other_reactant=1;first.other_mapping_index=4;a[0].push_back(first);EXPECT_THROW(NFsimTransformDecoder::decode(a),std::out_of_range);}
TEST(TransformDecoder_RejectsBindingPointingAtNonSecondHalf){std::vector<std::vector<NFsimPublicTransformView> > a(2);NFsimPublicTransformView first=v(NATIVE_BINDING,0,0);first.other_reactant=1;first.other_mapping_index=0;a[0].push_back(first);a[1].push_back(v(NATIVE_STATE_CHANGE,1,0));EXPECT_THROW(NFsimTransformDecoder::decode(a),std::logic_error);}
TEST(TransformDecoder_SkipsSecondBindingHalfAsIndependentOperation){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView second=v(NATIVE_BINDING,0,2);second.second_binding_half=true;a[0].push_back(second);EXPECT_TRUE(NFsimTransformDecoder::decode(a).empty());}
TEST(TransformDecoder_RemovePreservesRemovalType){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView x=v(NATIVE_REMOVE,0,0);x.removal_type=NATIVE_DELETE_MOLECULE_ONLY;a[0].push_back(x);EXPECT_EQ(NFsimTransformDecoder::decode(a)[0].removal_type,NATIVE_DELETE_MOLECULE_ONLY);}
TEST(TransformDecoder_EmptyTransformsAreIgnored){std::vector<std::vector<NFsimPublicTransformView> > a(1);a[0].push_back(v(NATIVE_EMPTY,0,0));EXPECT_TRUE(NFsimTransformDecoder::decode(a).empty());}
TEST(TransformDecoder_UnsupportedKindsRemainVisibleToFallbackLayer){std::vector<std::vector<NFsimPublicTransformView> > a(1);a[0].push_back(v(NATIVE_MOVE,0,0));std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),1u);EXPECT_EQ(o[0].kind,NATIVE_MOVE);}
TEST(TransformDecoder_PopulationSynthesisAndMoveMetadataSurvive){std::vector<std::vector<NFsimPublicTransformView> > a(1);NFsimPublicTransformView p=v(NATIVE_INCREMENT_POPULATION,0,0);p.population_delta=4;a[0].push_back(p);NFsimPublicTransformView add=v(NATIVE_ADD,0,0);add.added_molecule_type=2;a[0].push_back(add);NFsimPublicTransformView move=v(NATIVE_MOVE,0,0);move.destination_compartment=17;a[0].push_back(move);std::vector<NativeTransformSnapshot> o=NFsimTransformDecoder::decode(a);EXPECT_EQ(o.size(),3u);EXPECT_EQ(o[0].population_delta,4ll);EXPECT_EQ(o[1].added_molecule_type,2u);EXPECT_EQ(o[2].destination_compartment,17u);}
