#include "test_harness.hh"
#include "matcher.hh"
#include "scaffold.hh"
#include <limits>
using namespace NFcore2;

namespace {
CompiledModel matcherModel(){
    CompiledModel m;
    MoleculeTypeDescriptor a; a.name="A"; a.state_words=2; a.bond_slots=2; m.addMoleculeType(a);
    MoleculeTypeDescriptor b; b.name="B"; b.state_words=1; b.bond_slots=2; m.addMoleculeType(b);
    return m;
}
MatchContext contextFor(MoleculeTypeId t,MoleculeHandle h){ MatchContext c; c.type=t;c.molecule=h; return c; }
}

TEST(Scaffold_SparseCreateHasDeclaredLength){ ScaffoldStore s; ScaffoldId id=s.create(100,3,SCAFFOLD_SPARSE); EXPECT_EQ(s.length(id),100u); }
TEST(Scaffold_DenseCreateHasDeclaredLength){ ScaffoldStore s; ScaffoldId id=s.create(100,3,SCAFFOLD_DENSE); EXPECT_EQ(s.length(id),100u); }
TEST(Scaffold_SparseDefaultStateReturnedWithoutMaterialization){ ScaffoldStore s; ScaffoldId id=s.create(100000000,7,SCAFFOLD_SPARSE); EXPECT_EQ(s.state(id,99999999),7u); EXPECT_EQ(s.materializedStateCount(id),0u); }
TEST(Scaffold_SparseNonDefaultStateMaterializesOneEntry){ ScaffoldStore s; ScaffoldId id=s.create(100,0,SCAFFOLD_SPARSE); s.setState(id,50,2); EXPECT_EQ(s.state(id,50),2u); EXPECT_EQ(s.materializedStateCount(id),1u); }
TEST(Scaffold_SparseSettingDefaultRemovesException){ ScaffoldStore s; ScaffoldId id=s.create(100,1,SCAFFOLD_SPARSE); s.setState(id,2,8); s.setState(id,2,1); EXPECT_EQ(s.materializedStateCount(id),0u); EXPECT_EQ(s.state(id,2),1u); }
TEST(Scaffold_DenseMaterializedCountEqualsLength){ ScaffoldStore s; ScaffoldId id=s.create(37,4,SCAFFOLD_DENSE); EXPECT_EQ(s.materializedStateCount(id),37u); }
TEST(Scaffold_DenseStateRoundTrip){ ScaffoldStore s; ScaffoldId id=s.create(10,4,SCAFFOLD_DENSE); s.setState(id,3,9); EXPECT_EQ(s.state(id,3),9u); EXPECT_EQ(s.state(id,4),4u); }
TEST(Scaffold_PositionReadBoundsChecked){ ScaffoldStore s; ScaffoldId id=s.create(3); EXPECT_THROW(s.state(id,3),std::out_of_range); EXPECT_THROW(s.occupant(id,3),std::out_of_range); }
TEST(Scaffold_PositionWriteBoundsChecked){ ScaffoldStore s; ScaffoldId id=s.create(3); EXPECT_THROW(s.setState(id,3,1),std::out_of_range); EXPECT_THROW(s.setOccupant(id,3,MoleculeHandle(1,1)),std::out_of_range); }
TEST(Scaffold_InvalidIdBoundsChecked){ ScaffoldStore s; s.create(3); EXPECT_THROW(s.length(ScaffoldId(7)),std::out_of_range); }
TEST(Scaffold_ZeroLengthSupportsNoPositions){ ScaffoldStore s; ScaffoldId id=s.create(0); EXPECT_EQ(s.length(id),0u); EXPECT_THROW(s.state(id,0),std::out_of_range); }
TEST(Scaffold_SparseOccupantRoundTrip){ ScaffoldStore s; ScaffoldId id=s.create(100); MoleculeHandle h(3,4); s.setOccupant(id,12,h); EXPECT_EQ(s.occupant(id,12),h); EXPECT_EQ(s.occupiedCount(id),1u); }
TEST(Scaffold_SparseClearingOccupantErasesEntry){ ScaffoldStore s; ScaffoldId id=s.create(100); s.setOccupant(id,12,MoleculeHandle(3,4)); s.setOccupant(id,12,MoleculeHandle()); EXPECT_FALSE(s.occupant(id,12).valid()); EXPECT_EQ(s.occupiedCount(id),0u); }
TEST(Scaffold_DenseOccupantCountTracksMultiplePositions){ ScaffoldStore s; ScaffoldId id=s.create(10,0,SCAFFOLD_DENSE); s.setOccupant(id,1,MoleculeHandle(1,1)); s.setOccupant(id,7,MoleculeHandle(2,1)); EXPECT_EQ(s.occupiedCount(id),2u); s.setOccupant(id,1,MoleculeHandle()); EXPECT_EQ(s.occupiedCount(id),1u); }
TEST(Scaffold_SparseHugeLengthDoesNotMaterializeDefaultState){ ScaffoldStore s; ScaffoldId id=s.create(1000000000u,0,SCAFFOLD_SPARSE); for(unsigned i=0;i<100;++i) EXPECT_EQ(s.state(id,i*99991u),0u); EXPECT_EQ(s.materializedStateCount(id),0u); }

TEST(Matcher_TypeExistsAcceptsLiveMolecule){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle h=s.molecules(MoleculeTypeId(0)).create(); MatchContext c=contextFor(MoleculeTypeId(0),h); MatcherProgram p; p.add(MatchInstruction(MATCH_TYPE_EXISTS)); p.add(MatchInstruction(MATCH_END)); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_TypeExistsRejectsStaleMolecule){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle h=s.molecules(MoleculeTypeId(0)).create(); MatchContext c=contextFor(MoleculeTypeId(0),h); s.molecules(MoleculeTypeId(0)).erase(h); MatcherProgram p; p.add(MatchInstruction(MATCH_TYPE_EXISTS)); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_TypeExistsRejectsMissingSecondaryReactant){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MatcherProgram p; MatchInstruction x(MATCH_TYPE_EXISTS);x.target=1;p.add(x); MatchContext c; EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_StateMaskMatchesRequiredBits){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle h=s.molecules(MoleculeTypeId(0)).create(); s.molecules(MoleculeTypeId(0)).setStateWord(h,0,0b101101); MatchContext c=contextFor(MoleculeTypeId(0),h); MatcherProgram p; MatchInstruction x(MATCH_STATE_MASK);x.a=0;x.mask=0b1111;x.value=0b1101;p.add(x); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_StateMaskRejectsWrongBits){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle h=s.molecules(MoleculeTypeId(0)).create(); s.molecules(MoleculeTypeId(0)).setStateWord(h,0,0b101101); MatchContext c=contextFor(MoleculeTypeId(0),h); MatcherProgram p; MatchInstruction x(MATCH_STATE_MASK);x.a=0;x.mask=0b1111;x.value=0b0101;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_StateMaskCanReadSecondaryReactant){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(),b=s.molecules(MoleculeTypeId(1)).create(); s.molecules(MoleculeTypeId(1)).setStateWord(b,0,0x20); MatchContext c;c.setMoleculeAt(0,MoleculeRef(MoleculeTypeId(0),a));c.setMoleculeAt(1,MoleculeRef(MoleculeTypeId(1),b)); MatcherProgram p; MatchInstruction x(MATCH_STATE_MASK);x.target=1;x.a=0;x.mask=0x20;x.value=0x20;p.add(x); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_StateMaskRejectsMissingTargetRatherThanThrowing){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MatchContext c; MatcherProgram p; MatchInstruction x(MATCH_STATE_MASK);x.target=1;x.mask=1;x.value=1;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondPresentAcceptsTypedBond){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(),b=s.molecules(MoleculeTypeId(1)).create(); s.molecules(MoleculeTypeId(0)).setBondRef(a,0,MoleculeRef(MoleculeTypeId(1),b)); MatchContext c=contextFor(MoleculeTypeId(0),a); MatcherProgram p; MatchInstruction x(MATCH_BOND_PRESENT);x.a=0;p.add(x); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondPresentRejectsFreeSite){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(); MatchContext c=contextFor(MoleculeTypeId(0),a); MatcherProgram p; MatchInstruction x(MATCH_BOND_PRESENT);x.a=0;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondFreeAcceptsFreeSite){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(); MatchContext c=contextFor(MoleculeTypeId(0),a); MatcherProgram p; MatchInstruction x(MATCH_BOND_FREE);x.a=0;p.add(x); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondFreeRejectsOccupiedSite){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(),b=s.molecules(MoleculeTypeId(1)).create(); s.molecules(MoleculeTypeId(0)).setBondRef(a,0,MoleculeRef(MoleculeTypeId(1),b)); MatchContext c=contextFor(MoleculeTypeId(0),a); MatcherProgram p; MatchInstruction x(MATCH_BOND_FREE);x.a=0;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondFreeRejectsMissingSecondaryTarget){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MatchContext c; MatcherProgram p; MatchInstruction x(MATCH_BOND_FREE);x.target=1;x.a=0;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondToAcceptsExactTypedPartner){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(),b=s.molecules(MoleculeTypeId(1)).create(); s.molecules(MoleculeTypeId(0)).setBondRef(a,1,MoleculeRef(MoleculeTypeId(1),b)); MatchContext c;c.setMoleculeAt(0,MoleculeRef(MoleculeTypeId(0),a));c.setMoleculeAt(1,MoleculeRef(MoleculeTypeId(1),b)); MatcherProgram p; MatchInstruction x(MATCH_BOND_TO);x.a=1;x.b=1;p.add(x); EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_BondToRejectsDifferentPartner){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle a=s.molecules(MoleculeTypeId(0)).create(),b=s.molecules(MoleculeTypeId(1)).create(),c2=s.molecules(MoleculeTypeId(1)).create(); s.molecules(MoleculeTypeId(0)).setBondRef(a,1,MoleculeRef(MoleculeTypeId(1),b)); MatchContext c;c.setMoleculeAt(0,MoleculeRef(MoleculeTypeId(0),a));c.setMoleculeAt(1,MoleculeRef(MoleculeTypeId(1),c2)); MatcherProgram p; MatchInstruction x(MATCH_BOND_TO);x.a=1;x.b=1;p.add(x); EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_PopulationThresholdAtEquality){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; PopulationId p0=s.populations().add(5); MatcherProgram p; MatchInstruction x(MATCH_POPULATION_AT_LEAST);x.a=p0.value();x.value=5;p.add(x); MatchContext c; EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_PopulationThresholdRejectsBelow){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; PopulationId p0=s.populations().add(4); MatcherProgram p; MatchInstruction x(MATCH_POPULATION_AT_LEAST);x.a=p0.value();x.value=5;p.add(x); MatchContext c; EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_ScaffoldStateMatchesOffset){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; ScaffoldId id=sc.create(20);sc.setState(id,12,3); MatchContext c;c.scaffold=id;c.coordinate=10; MatcherProgram p;MatchInstruction x(MATCH_SCAFFOLD_STATE);x.a=2;x.value=3;p.add(x);EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_ScaffoldStateRejectsWrongValue){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; ScaffoldId id=sc.create(20); MatchContext c;c.scaffold=id;c.coordinate=10; MatcherProgram p;MatchInstruction x(MATCH_SCAFFOLD_STATE);x.a=2;x.value=3;p.add(x);EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_ScaffoldFreeAcceptsEmptyPosition){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; ScaffoldId id=sc.create(20); MatchContext c;c.scaffold=id;c.coordinate=10; MatcherProgram p;MatchInstruction x(MATCH_SCAFFOLD_FREE);x.a=2;p.add(x);EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_ScaffoldFreeRejectsOccupiedPosition){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; ScaffoldId id=sc.create(20); sc.setOccupant(id,12,MoleculeHandle(1,1)); MatchContext c;c.scaffold=id;c.coordinate=10; MatcherProgram p;MatchInstruction x(MATCH_SCAFFOLD_FREE);x.a=2;p.add(x);EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_EndStopsEvaluation){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MatcherProgram p; p.add(MatchInstruction(MATCH_END)); MatchInstruction x(MATCH_POPULATION_AT_LEAST);x.a=99;x.value=1;p.add(x);MatchContext c;EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_EmptyProgramVacuouslyMatches){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MatcherProgram p; MatchContext c; EXPECT_TRUE(p.evaluate(s,sc,c)); }
TEST(Matcher_CompoundProgramRequiresAllPredicates){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; MoleculeHandle h=s.molecules(MoleculeTypeId(0)).create();s.molecules(MoleculeTypeId(0)).setStateWord(h,0,3);MatchContext c=contextFor(MoleculeTypeId(0),h);MatcherProgram p;p.add(MatchInstruction(MATCH_TYPE_EXISTS));MatchInstruction x(MATCH_STATE_MASK);x.mask=3;x.value=3;p.add(x);MatchInstruction y(MATCH_BOND_FREE);y.a=0;p.add(y);p.add(MatchInstruction(MATCH_END));EXPECT_TRUE(p.evaluate(s,sc,c));s.molecules(MoleculeTypeId(0)).setStateWord(h,0,2);EXPECT_FALSE(p.evaluate(s,sc,c)); }
TEST(Matcher_ScaffoldOffsetOverflowIsRejected){ CompiledModel m=matcherModel(); SimulationState s(m); ScaffoldStore sc; ScaffoldId id=sc.create(10);MatchContext c;c.scaffold=id;c.coordinate=std::numeric_limits<std::uint32_t>::max();MatcherProgram p;MatchInstruction x(MATCH_SCAFFOLD_FREE);x.a=2;p.add(x);EXPECT_THROW(p.evaluate(s,sc,c),std::out_of_range); }
