#include "test_harness.hh"
#include "simulation_state.hh"
#include <random>
using namespace NFcore2;
static CompiledModel gm(){CompiledModel m;for(int t=0;t<4;++t){MoleculeTypeDescriptor d;d.name="T";d.state_words=3;d.bond_slots=4;m.addMoleculeType(d);}return m;}
TEST(erase_clears_all_reciprocal_cross_type_bonds){auto m=gm();SimulationState s(m);auto a=s.molecules(MoleculeTypeId(0)).create();std::vector<MoleculeRef> bs;for(unsigned t=1;t<4;++t){auto h=s.molecules(MoleculeTypeId(t)).create();bs.push_back({MoleculeTypeId(t),h});s.molecules(MoleculeTypeId(0)).setBondRef(a,t-1,bs.back());s.molecules(MoleculeTypeId(t)).setBondRef(h,0,{MoleculeTypeId(0),a});}EXPECT_TRUE(s.eraseMolecule({MoleculeTypeId(0),a}));for(auto b:bs)EXPECT_FALSE(s.molecules(b.type).bondRef(b.handle,0).valid());}
TEST(generation_reuse_never_resurrects_old_references){auto m=gm();SimulationState s(m);auto a=s.molecules(MoleculeTypeId(0)).create();auto b=s.molecules(MoleculeTypeId(1)).create();s.molecules(MoleculeTypeId(1)).setBondRef(b,0,{MoleculeTypeId(0),a});s.molecules(MoleculeTypeId(0)).setBondRef(a,0,{MoleculeTypeId(1),b});EXPECT_TRUE(s.eraseMolecule({MoleculeTypeId(0),a}));auto a2=s.molecules(MoleculeTypeId(0)).create();EXPECT_EQ(a.slot,a2.slot);EXPECT_NE(a.generation,a2.generation);EXPECT_FALSE(s.molecules(MoleculeTypeId(1)).bondRef(b,0).valid());}
TEST(random_create_delete_reuse_preserves_live_count_reference){auto m=gm();SimulationState s(m);std::vector<MoleculeHandle> live;std::mt19937 g(555);for(unsigned step=0;step<200000;++step){if(live.empty()||(g()%3)){auto h=s.molecules(MoleculeTypeId(0)).create();live.push_back(h);}else{size_t i=g()%live.size();EXPECT_TRUE(s.molecules(MoleculeTypeId(0)).erase(live[i]));live[i]=live.back();live.pop_back();}EXPECT_EQ(s.molecules(MoleculeTypeId(0)).liveCount(),live.size());if((step%1009)==0)for(auto h:live)EXPECT_TRUE(s.molecules(MoleculeTypeId(0)).alive(h));}}
TEST(state_words_are_independent_across_slots_and_generations){auto m=gm();SimulationState s(m);std::vector<MoleculeHandle>v;for(unsigned i=0;i<1000;++i){auto h=s.molecules(MoleculeTypeId(2)).create();v.push_back(h);for(unsigned w=0;w<3;++w)s.molecules(MoleculeTypeId(2)).setStateWord(h,w,((uint64_t)i<<32)|w);}for(unsigned i=0;i<v.size();++i)for(unsigned w=0;w<3;++w)EXPECT_EQ(s.molecules(MoleculeTypeId(2)).stateWord(v[i],w),((uint64_t)i<<32)|w);}
TEST(stale_state_access_throws_after_delete){auto m=gm();SimulationState s(m);auto h=s.molecules(MoleculeTypeId(0)).create();s.molecules(MoleculeTypeId(0)).erase(h);EXPECT_THROW(s.molecules(MoleculeTypeId(0)).stateWord(h,0),std::exception);EXPECT_THROW(s.molecules(MoleculeTypeId(0)).setStateWord(h,0,1),std::exception);}
