#include "test_harness.hh"
#include "rule_compiler.hh"
#include <algorithm>
#include <random>
using namespace NFcore2;
static RuleInstanceIR ri(unsigned family,unsigned coord){RuleInstanceIR r;r.name="r";r.matcher_signature="m"+std::to_string(family);r.transform_signature="t"+std::to_string(family%3);r.matcher=MatcherId(family);r.transform=TransformProgramId(family%3);r.rate=1.0+coord*.001;r.parameter_index=coord%11;r.coordinate=coord;return r;}
TEST(million_logical_rules_compress_to_expected_families){std::vector<RuleInstanceIR>v;v.reserve(1000000);for(unsigned i=0;i<1000000;++i)v.push_back(ri(i%20,i));auto c=RuleFamilyCompiler::compile(v);EXPECT_EQ(c.families.size(),20u);size_t n=0;for(auto&f:c.families)n+=f.members.size();EXPECT_EQ(n,1000000u);}
TEST(instance_mapping_round_trips_every_member){std::vector<RuleInstanceIR>v;for(unsigned i=0;i<20000;++i)v.push_back(ri((i*17)%31,i));auto c=RuleFamilyCompiler::compile(v);for(unsigned i=0;i<v.size();++i){auto fid=c.instance_to_family[i].value();auto mid=c.instance_to_member[i];EXPECT_TRUE(fid<c.families.size());EXPECT_TRUE(mid<c.families[fid].members.size());EXPECT_EQ(c.families[fid].members[mid].coordinate,v[i].coordinate);EXPECT_NEAR(c.families[fid].members[mid].rate,v[i].rate,0.0);}}
TEST(rule_input_permutation_does_not_change_partition_equivalence){std::vector<RuleInstanceIR>a;for(unsigned i=0;i<10000;++i)a.push_back(ri(i%13,i));std::vector<RuleInstanceIR>b=a;std::mt19937 g(9);std::shuffle(b.begin(),b.end(),g);auto x=RuleFamilyCompiler::compile(a),y=RuleFamilyCompiler::compile(b);EXPECT_EQ(x.families.size(),y.families.size());std::vector<size_t>xs,ys;for(auto&f:x.families)xs.push_back(f.members.size());for(auto&f:y.families)ys.push_back(f.members.size());std::sort(xs.begin(),xs.end());std::sort(ys.begin(),ys.end());EXPECT_EQ(xs,ys);}
TEST(rate_differences_do_not_split_structural_family){std::vector<RuleInstanceIR>v;for(unsigned i=0;i<1000;++i){auto r=ri(0,i);r.rate=(i+1)*3.14159;v.push_back(r);}auto c=RuleFamilyCompiler::compile(v);EXPECT_EQ(c.families.size(),1u);EXPECT_EQ(c.families[0].members.size(),1000u);}
TEST(matcher_signature_difference_splits_even_same_ids){auto a=ri(0,0),b=a;b.matcher_signature="different";std::vector<RuleInstanceIR>v={a,b};auto c=RuleFamilyCompiler::compile(v);EXPECT_EQ(c.families.size(),2u);}
TEST(transform_signature_difference_splits_even_same_ids){auto a=ri(0,0),b=a;b.transform_signature="different";std::vector<RuleInstanceIR>v={a,b};auto c=RuleFamilyCompiler::compile(v);EXPECT_EQ(c.families.size(),2u);}
TEST(nonfinite_rates_are_rejected){auto a=ri(0,0);a.rate=std::numeric_limits<double>::quiet_NaN();EXPECT_THROW(RuleFamilyCompiler::compile(std::vector<RuleInstanceIR>(1,a)),std::invalid_argument);a.rate=std::numeric_limits<double>::infinity();EXPECT_THROW(RuleFamilyCompiler::compile(std::vector<RuleInstanceIR>(1,a)),std::invalid_argument);}
