#include "model_image.hh"
#include <fstream>
#include <stdexcept>
#include <cstring>
namespace NFcore2 {
const std::uint32_t ModelImage::FORMAT_VERSION;
namespace {
template<class T> void put(std::ostream&o,const T&v){o.write(reinterpret_cast<const char*>(&v),sizeof(T));if(!o)throw std::runtime_error("NFcore2 model image write failed");}
template<class T> T get(std::istream&i){T v;i.read(reinterpret_cast<char*>(&v),sizeof(T));if(!i)throw std::runtime_error("NFcore2 model image truncated");return v;}
void putString(std::ostream&o,const std::string&s){std::uint32_t n=(std::uint32_t)s.size();put(o,n);o.write(s.data(),n);if(!o)throw std::runtime_error("NFcore2 string write failed");}
std::string getString(std::istream&i){std::uint32_t n=get<std::uint32_t>(i);if(n>100000000u)throw std::runtime_error("NFcore2 invalid string length");std::string s(n,'\0');if(n)i.read(&s[0],n);if(!i)throw std::runtime_error("NFcore2 string truncated");return s;}
}
void ModelImage::write(const ExecutableModel&m,std::ostream&o){const char magic[8]={'N','F','S','2','I','M','G','1'};o.write(magic,8);put(o,FORMAT_VERSION);
 const std::vector<MoleculeTypeDescriptor>&ts=m.metadata().moleculeTypes();put(o,(std::uint32_t)ts.size());for(std::size_t i=0;i<ts.size();++i){putString(o,ts[i].name);put(o,ts[i].state_words);put(o,ts[i].bond_slots);put(o,(std::uint8_t)(ts[i].population?1:0));}
 const std::vector<FeatureDescriptor>&fs=m.metadata().features();put(o,(std::uint32_t)fs.size());for(std::size_t i=0;i<fs.size();++i){put(o,(std::uint32_t)fs[i].kind);put(o,fs[i].owner);put(o,fs[i].index);}
 const std::vector<MatcherProgram>&mp=m.matchers().programs();put(o,(std::uint32_t)mp.size());for(std::size_t i=0;i<mp.size();++i){const std::vector<MatchInstruction>&c=mp[i].code();put(o,(std::uint32_t)c.size());for(std::size_t j=0;j<c.size();++j){put(o,(std::uint32_t)c[j].opcode);put(o,c[j].target);put(o,c[j].a);put(o,c[j].b);put(o,c[j].mask);put(o,c[j].value);put(o,(std::uint8_t)(c[j].check_partner_component?1:0));}}
 const std::vector<TransformProgram>&tp=m.transforms().programs();put(o,(std::uint32_t)tp.size());for(std::size_t i=0;i<tp.size();++i){const std::vector<TransformInstruction>&c=tp[i].code();put(o,(std::uint32_t)c.size());for(std::size_t j=0;j<c.size();++j){put(o,(std::uint32_t)c[j].opcode);put(o,c[j].target);put(o,c[j].other);put(o,c[j].a);put(o,c[j].b);put(o,c[j].value);put(o,c[j].feature.value());}}
 const std::vector<RuleFamilyDescriptor>&rf=m.metadata().ruleFamilies();put(o,(std::uint32_t)rf.size());for(std::size_t i=0;i<rf.size();++i){putString(o,rf[i].name);put(o,rf[i].matcher.value());put(o,rf[i].transform.value());put(o,(std::uint8_t)(rf[i].uniform_rate?1:0));put(o,(std::uint32_t)rf[i].members.size());for(std::size_t j=0;j<rf[i].members.size();++j){const RuleMember& member=rf[i].members[j];put(o,member.rate);put(o,member.parameter_index);put(o,member.coordinate);put(o,(std::uint32_t)member.rate_law.kind);put(o,member.rate_law.target);put(o,member.rate_law.partner_target);put(o,member.rate_law.component);put(o,member.rate_law.partner_component);put(o,member.rate_law.offset);put(o,member.rate_law.slope);put(o,member.rate_law.weight);}}
 const DependencyIndex&di=m.metadata().dependencies();put(o,(std::uint32_t)di.offsets.size());for(std::size_t i=0;i<di.offsets.size();++i)put(o,di.offsets[i]);put(o,(std::uint32_t)di.matchers.size());for(std::size_t i=0;i<di.matchers.size();++i)put(o,di.matchers[i].value());
}
ExecutableModel ModelImage::read(std::istream&i){char magic[8];i.read(magic,8);const char expected[8]={'N','F','S','2','I','M','G','1'};if(!i||std::memcmp(magic,expected,8)!=0)throw std::runtime_error("not an NFcore2 model image");std::uint32_t version=get<std::uint32_t>(i);if(version!=FORMAT_VERSION)throw std::runtime_error("unsupported NFcore2 model image version");ExecutableModel m;CompiledModel&cm=m.buildMetadata();
 std::uint32_t n=get<std::uint32_t>(i);for(std::uint32_t x=0;x<n;++x){MoleculeTypeDescriptor d;d.name=getString(i);d.state_words=get<std::uint16_t>(i);d.bond_slots=get<std::uint16_t>(i);d.population=get<std::uint8_t>(i)!=0;cm.addMoleculeType(d);}n=get<std::uint32_t>(i);for(std::uint32_t x=0;x<n;++x){FeatureDescriptor d;d.kind=(FeatureKind)get<std::uint32_t>(i);d.owner=get<std::uint32_t>(i);d.index=get<std::uint32_t>(i);cm.addFeature(d);}
 n=get<std::uint32_t>(i);for(std::uint32_t x=0;x<n;++x){MatcherProgram p;std::uint32_t q=get<std::uint32_t>(i);for(std::uint32_t y=0;y<q;++y){MatchInstruction z(static_cast<std::uint16_t>(get<std::uint32_t>(i)));z.target=get<std::uint16_t>(i);z.a=get<std::uint32_t>(i);z.b=get<std::uint32_t>(i);z.mask=get<std::uint64_t>(i);z.value=get<std::uint64_t>(i);z.check_partner_component=get<std::uint8_t>(i)!=0;p.add(z);}m.buildMatchers().add(p);}
 n=get<std::uint32_t>(i);for(std::uint32_t x=0;x<n;++x){TransformProgram p;std::uint32_t q=get<std::uint32_t>(i);for(std::uint32_t y=0;y<q;++y){TransformInstruction z(static_cast<std::uint16_t>(get<std::uint32_t>(i)));z.target=get<std::uint16_t>(i);z.other=get<std::uint16_t>(i);z.a=get<std::uint32_t>(i);z.b=get<std::uint32_t>(i);z.value=get<std::uint64_t>(i);z.feature=FeatureId(get<std::uint32_t>(i));p.add(z);}m.buildTransforms().add(p);}
 n=get<std::uint32_t>(i);for(std::uint32_t x=0;x<n;++x){RuleFamilyDescriptor f;f.name=getString(i);f.matcher=MatcherId(get<std::uint32_t>(i));f.transform=TransformProgramId(get<std::uint32_t>(i));f.uniform_rate=get<std::uint8_t>(i)!=0;std::uint32_t q=get<std::uint32_t>(i);f.members.resize(q);for(std::uint32_t y=0;y<q;++y){RuleMember& member=f.members[y];member.rate=get<double>(i);member.parameter_index=get<std::uint32_t>(i);member.coordinate=get<std::uint32_t>(i);member.rate_law.kind=(RateLawKind)get<std::uint32_t>(i);member.rate_law.target=get<std::uint16_t>(i);member.rate_law.partner_target=get<std::uint16_t>(i);member.rate_law.component=get<std::uint32_t>(i);member.rate_law.partner_component=get<std::uint32_t>(i);member.rate_law.offset=get<double>(i);member.rate_law.slope=get<double>(i);member.rate_law.weight=get<double>(i);}cm.addRuleFamily(f);}std::uint32_t no=get<std::uint32_t>(i);std::vector<std::uint32_t> offsets(no);for(std::uint32_t x=0;x<no;++x)offsets[x]=get<std::uint32_t>(i);std::uint32_t nm=get<std::uint32_t>(i);std::vector<MatcherId> flat(nm);for(std::uint32_t x=0;x<nm;++x)flat[x]=MatcherId(get<std::uint32_t>(i));std::vector<std::vector<MatcherId> >adj(cm.features().size());if(no==cm.features().size()+1){for(std::size_t f=0;f<cm.features().size();++f){if(offsets[f]>offsets[f+1]||offsets[f+1]>flat.size())throw std::runtime_error("invalid NFcore2 dependency index");adj[f].insert(adj[f].end(),flat.begin()+offsets[f],flat.begin()+offsets[f+1]);}}else if(no!=0)throw std::runtime_error("invalid NFcore2 dependency offsets");cm.setFeatureDependencies(adj);m.validate();return m;}
void ModelImage::writeFile(const ExecutableModel&m,const std::string&p){std::ofstream o(p.c_str(),std::ios::binary);if(!o)throw std::runtime_error("cannot open NFcore2 model image for writing");write(m,o);}
ExecutableModel ModelImage::readFile(const std::string&p){std::ifstream i(p.c_str(),std::ios::binary);if(!i)throw std::runtime_error("cannot open NFcore2 model image");return read(i);}
}
